/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_netbeans_lib_profiler_server_system_Timers */

#ifndef _Included_org_netbeans_lib_profiler_server_system_Timers
#define _Included_org_netbeans_lib_profiler_server_system_Timers
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_netbeans_lib_profiler_server_system_Timers
 * Method:    getThreadCPUTimeInNanos
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_netbeans_lib_profiler_server_system_Timers_getThreadCPUTimeInNanos
  (JNIEnv *, jclass);

/*
 * Class:     org_netbeans_lib_profiler_server_system_Timers
 * Method:    enableMicrostateAccounting
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_netbeans_lib_profiler_server_system_Timers_enableMicrostateAccounting
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     org_netbeans_lib_profiler_server_system_Timers
 * Method:    osSleep
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_netbeans_lib_profiler_server_system_Timers_osSleep
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
