/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_netbeans_lib_profiler_server_system_GC */

#ifndef _Included_org_netbeans_lib_profiler_server_system_GC
#define _Included_org_netbeans_lib_profiler_server_system_GC
#ifdef __cplusplus
extern "C" {
#endif
#undef org_netbeans_lib_profiler_server_system_GC_OBSERVED_PERIODS
#define org_netbeans_lib_profiler_server_system_GC_OBSERVED_PERIODS 10L
/*
 * Class:     org_netbeans_lib_profiler_server_system_GC
 * Method:    getCurrentGCEpoch
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_netbeans_lib_profiler_server_system_GC_getCurrentGCEpoch
  (JNIEnv *, jclass);

/*
 * Class:     org_netbeans_lib_profiler_server_system_GC
 * Method:    getGCRelativeTimeMetrics
 * Signature: ([J)V
 */
JNIEXPORT void JNICALL Java_org_netbeans_lib_profiler_server_system_GC_getGCRelativeTimeMetrics
  (JNIEnv *, jclass, jlongArray);

/*
 * Class:     org_netbeans_lib_profiler_server_system_GC
 * Method:    getGCStartFinishTimes
 * Signature: ([J[J)V
 */
JNIEXPORT void JNICALL Java_org_netbeans_lib_profiler_server_system_GC_getGCStartFinishTimes
  (JNIEnv *, jclass, jlongArray, jlongArray);

/*
 * Class:     org_netbeans_lib_profiler_server_system_GC
 * Method:    activateGCEpochCounter
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_netbeans_lib_profiler_server_system_GC_activateGCEpochCounter
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     org_netbeans_lib_profiler_server_system_GC
 * Method:    objectsAdjacent
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_netbeans_lib_profiler_server_system_GC_objectsAdjacent
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     org_netbeans_lib_profiler_server_system_GC
 * Method:    resetGCEpochCounter
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_netbeans_lib_profiler_server_system_GC_resetGCEpochCounter
  (JNIEnv *, jclass);

/*
 * Class:     org_netbeans_lib_profiler_server_system_GC
 * Method:    runGC
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_netbeans_lib_profiler_server_system_GC_runGC
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
